import re

from mitmproxy.http import HTTPFlow

drop_hosts = [
    r".*\.tavoos\.net$",
    r".*\.mediaad\.org$",
    r".*\.webengage\.com$",
    r".*\.adtrace\.io$",
    r".*s\.clarity\.ms$",
    r".*clarity\.ms$",
    r".*www\.gstatic\.com$",
    r".*google-analytics\.com$",
    r".*analytics\.google\.com$",
    r".*ssl\.google-analytics\.com$",
    r".*optimizationguide-pa\.googleapis\.com$",
    r".*content-autofill\.googleapis\.com$",
    r".*pagead2\.googlesyndication\.com$",
    r".*pagead-googlehosted\.l\.google\.com$",
    r".*tpc\.googlesyndication\.com$",
    r".*partner\.googleadservices\.com$",
    r".*googleads\.g\.doubleclick\.net$",
    r".*adservice\.google\.com$",
    r".*adservice\.google\.co\.in$",
    r".*connect\.facebook\.net$",
    r".*www\.facebook\.com/tr$",
    r".*graph\.facebook\.com$",
    r".*analytics\.tiktok\.com$",
    r".*business\.tiktok\.com$",
    r".*snap\.licdn\.com$",
    r".*px\.ads\.linkedin\.com$",
    r".*analytics\.twitter\.com$",
    r".*static\.ads-twitter\.com$",
    r".*static\.hotjar\.com$",
    r".*script\.hotjar\.com$",
    r".*insights\.hotjar\.com$",
    r".*cdn\.segment\.com$",
    r".*api\.segment\.io$",
    r".*cdn\.mxpnl\.com$",
    r".*api\.mixpanel\.com$",
    r".*api\.amplitude\.com$",
    r".*track\.hubspot\.com$",
    r".*js\.hs-analytics\.net$",
    r".*forms\.hsforms\.com$",
    r".*script\.crazyegg\.com$",
    r".*omtrdc\.net$",
    r".*sc\.omtrdc\.net$",
    r".*metrics\.adobe\.com$",
    r".*doubleclick\.net$",
    r".*googletagmanager\.com$",
    r".*googletagservices\.com$",
    r".*criteo\.com$",
    r".*ads\.yahoo\.com$",
    r".*adsrvr\.org$",
    r".*adnxs\.com$",
    r".*scorecardresearch\.com$",
    r".*quantserve\.com$",
    r".*mathtag\.com$",
    r".*bluekai\.com$",
    r".*tapad\.com$",
    r".*yieldmo\.com$",
    r".*moatads\.com$",
]


def request(flow: HTTPFlow):
    if any(re.search(p, flow.request.host) for p in drop_hosts):
        flow.kill()
